package shared.exceptions;

public class ComputationFinishedException extends RuntimeException {

}
